server:
  port: 10001

spring:
  application:
    name: consumer

service:
  version: 1.0.0


dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 60000
